### ISSUE TITLE
Add functionality to main menu

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Taleon#12]
Currently, the main menu doesn't do anything but look pretty (sort of).
It's exit button shall close the application and it's start button shall load the Demo scene (Assets/Scenes/Chapters/Demo.unity)   (and hide the main menu).

**Comment by oleg-abr** [comment]
Strangely enough, I do not have Chapters order, after fetching the latest. But I can see it is online, here, on github.
