### ISSUE TITLE
Name second faction

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Taleon#4]
Decide on a (non-final) name for the 2nd faction that is encountered in the demo.
It will probably serve as the primary antagonist in the demo.

Write up its history and place the result in the story folder.

**Comment by oleg-abr** [comment]
@Kittyfisto 

This contrast a bit with the proposed story outline, but hey! 

Political situation.
------------------------------
The federal governments have ceded most of their power to corporations and entrepreneurs, which all started in the 21st century with the reign of Donald Trump's "Make America great again". Withdrawing from the Trans-Pacific Partnership (TPP) trade pact was strongly against the will of corporate expansion. The lifeblood of the global economy is international trade and the free flow of labor and capital, and so the corporations gradually took over. The remnants of governments maintain authority only in isolated compounds/colonies, by and large, irrelevant to the dynamic society around them.

Corporative and private vehicles reign supreme over the space. Mercenary armies/fleets compete for corporations' defense contracts. 
My protagonist (2nd faction) is the mercenary fleet named "Iskander" arisen from the Russian Red Army's Air Force. Its unique selling point is a hacking squad, which is powering down the enemy's defenses prior to attack.

**Comment by Kittyfisto** [comment]
*Chuckle* I don't know how "political" this game should get but it's a fun explanation of how corporations got so much power.

Love the name, we'll definitely have to use it. The use of ECM (electronic counter measures, aka hacking) hadn't occurred to me yet, but that might offer another system for the player to balance.
