### ISSUE TITLE
Write (rough) outline for the first playable mission.

### ISSUE THREAD

**Issue by Kittyfisto** [Kittyfisto/Taleon#5]
Decide upon what the first playable mission shall be about.

The outline shall include:
- Who is the protagonist?
- Where is the mission taking place?
- What is the player supposed to do? (win condition)
- Are there any lose conditions other than dying?
- What type of enemies does the player encounter?

The result shall be placed in the story folder.

**Comment by Kittyfisto** [comment]
@oleg-abr What do you think of making this mission about simulated combat?
We could do something along the lines of:

- Cutscene: Ship introduction and location introduction (orbital of the player's faction)
- Undock ship from station (player's first contact with navigation by "driving" out of the docking bay)
- "Test" of ship's RCS thrusters (show player how to move and rotate the ship via thruster)
- "Test" of ship's main engine (i.e. fly the ship away from the station)
- "Test" of ship's weapons systems
- Maybe followed by an actual (unexpected) engagement

**Comment by oleg-abr** [comment]
@Kittyfisto 
An actual engagement, unexpected or expected (it doesn't matter) could be just destroying debris to clear the obstacle for the freighter. This way an "opponent" is passive, isn't actively shooting and maneuvering, and our player can learn the control of the ship as well as its defence and weapon systems.
